defaults:
  - trainer: default.yaml
  - callbacks: default.yaml
  - model: fe.yaml
  - optimizer: adam.yaml
  - datamodule: ???

# Seed
seed: 42

# Metric to optimize
optimized_metric: 'val/f1-score'

# ClearML config
task_name: ???
use_clearml: True

debug: true
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# disable python warnings if they annoy you
ignore_warnings: True