defaults:
  - trainer: default.yaml
  - logger: clearml.yaml
  - callbacks: default.yaml
  - model: fe.yaml
  - optimizer: adam.yaml
  - datamodule: ???

debug: true

work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

# disable python warnings if they annoy you
ignore_warnings: True